variables:
  CLI_VERSION: 6.1.5
  DIST_DIR: dist/
  
stages:
  - init
  - test
  - build

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - src/webapp/client/node_modules

before_script:
- cd src/webapp/client
- "[ -d node_modules ] || npm ci"

init:
  stage: init
  image: trion/ng-cli-karma:${CLI_VERSION}
  script: ['']
  cache:
    policy: pull-push
    key: ${CI_COMMIT_SHA}
    paths: ['src/webapp/client/node_modules']

lint:nglint:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: true
  script:
    - ng lint

frontend:test:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
    - ./node_modules/@angular/cli/bin/ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - src/webapp/client/coverage/

frontend:build:
  stage: build
  image: trion/ng-cli-karma:${CLI_VERSION}
  needs: ["frontend:test"]
  script:
    - ./node_modules/@angular/cli/bin/ng build --prod 
  artifacts:
    expire_in: 1 day
    paths:
      - src/webapp/client/$DIST_DIR

backend:test:
  stage: test
  before_script: ['']
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: true
  script:
    - cd src/webapp/server
    - npm install
    - npm test
  cache:
    policy: pull-push
    key: ${CI_COMMIT_SHA}
    paths: ['src/webapp/server/node_modules']
