image: node:8.17.0

cache:
  paths:
    - src/webapp/server/node_modules

stages:
  - BackendTests

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - src/webapp/server/node_modules

expresstests:
  stage: BackendTests
  script:
    - cd src/webapp/server
    - npm install
    - npm start &
    - npm test
only:
  refs :
    - master
    - webapp/*
  changes:
    - src/webapp/*